FROM eclipse-temurin:25-jdk

WORKDIR /app

COPY gradle/ gradle/
COPY gradlew build.gradle settings.gradle gradle.properties ./
RUN ./gradlew dependencies --no-daemon

COPY src ./src

EXPOSE 8080 5005

CMD ["./gradlew", "bootRun", "-Pdebug=true", "--no-daemon"]